version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3306
        networks:
            mynetwork:
                aliases:
                    - db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - mynetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - mynetwork

networks:
    mynetwork:
